const pizzaBtn = document.querySelector(".pizza-btn");
      const wrapBtn = document.querySelector(".wrap-btn");
      const chipsBtn = document.querySelector(".chips-btn");
      const burgersBtn = document.querySelector(".burger-btn");
      const specialboxBtn = document.querySelector(".special-box-btn");
      const sideordersBtn = document.querySelector(".side-orders-btn");
      const chickenBtn = document.querySelector(".chicken-btn");
      const kebabBtn = document.querySelector(".kebab-btn");
      const mealsBtn = document.querySelector(".meals-btn");
      const drinksBtn = document.querySelector(".drinks-btn");

      const pizzaTable = document.querySelector("#pizza-table");
      const wrapTable = document.querySelector("#wrap-table");
      const chipsTable = document.querySelector("#chips-table");
      const burgersTable = document.querySelector("#burgers-table");
      const specialboxTable = document.querySelector("#special-boxes-table");
      const sideordersTable = document.querySelector("#side-orders-table");
      const chickenTable = document.querySelector("#chicken-table");
      const kebabTable = document.querySelector("#kebab-table");
      const mealsTable = document.querySelector("#meals-table");
      const drinksTable = document.querySelector("#drinks-table");

      pizzaBtn.addEventListener("click", function () {
        pizzaTable.style.display = "table";
        wrapTable.style.display = "none";
        chipsTable.style.display = "none";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "none";
        kebabTable.style.display = "none";
        mealsTable.style.display = "none";
        drinksTable.style.display = "none";
        pizzaBtn.classList.add("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.remove("active");
      });

      wrapBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "table";
        chipsTable.style.display = "none";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "none";
        kebabTable.style.display = "none";
        mealsTable.style.display = "none";
        drinksTable.style.display = "none";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.add("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.remove("active");
      });

      chipsBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "none";
        chipsTable.style.display = "table";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "none";
        kebabTable.style.display = "none";
        mealsTable.style.display = "none";
        drinksTable.style.display = "none";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.add("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.remove("active");
      });

      burgersBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "none";
        chipsTable.style.display = "none";
        burgersTable.style.display = "table";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "none";
        kebabTable.style.display = "none";
        mealsTable.style.display = "none";
        drinksTable.style.display = "none";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.add("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.remove("active");
      });

      specialboxBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "none";
        chipsTable.style.display = "none";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "table";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "none";
        kebabTable.style.display = "none";
        mealsTable.style.display = "none";
        drinksTable.style.display = "none";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.add("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.remove("active");
      });

      sideordersBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "none";
        chipsTable.style.display = "none";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "table";
        chickenTable.style.display = "none";
        kebabTable.style.display = "none";
        mealsTable.style.display = "none";
        drinksTable.style.display = "none";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.add("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.remove("active");
      });

      chickenBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "none";
        chipsTable.style.display = "none";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "table";
        kebabTable.style.display = "none";
        mealsTable.style.display = "none";
        drinksTable.style.display = "none";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.add("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.remove("active");
      });

      kebabBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "none";
        chipsTable.style.display = "none";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "none";
        kebabTable.style.display = "table";
        mealsTable.style.display = "none";
        drinksTable.style.display = "none";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.add("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.remove("active");
      });

      mealsBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "none";
        chipsTable.style.display = "none";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "none";
        kebabTable.style.display = "none";
        mealsTable.style.display = "table";
        drinksTable.style.display = "none";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.add("active");
        drinksBtn.classList.remove("active");
      });

      drinksBtn.addEventListener("click", function () {
        pizzaTable.style.display = "none";
        wrapTable.style.display = "none";
        chipsTable.style.display = "none";
        burgersTable.style.display = "none";
        specialboxTable.style.display = "none";
        sideordersTable.style.display = "none";
        chickenTable.style.display = "none";
        kebabTable.style.display = "none";
        mealsTable.style.display = "none";
        drinksTable.style.display = "table";
        pizzaBtn.classList.remove("active");
        wrapBtn.classList.remove("active");
        chipsBtn.classList.remove("active");
        burgersBtn.classList.remove("active");
        specialboxBtn.classList.remove("active");
        sideordersBtn.classList.remove("active");
        chickenBtn.classList.remove("active");
        kebabBtn.classList.remove("active");
        mealsBtn.classList.remove("active");
        drinksBtn.classList.add("active");
      });